# Configuración de sponsors para GitHub
# Puedes habilitar múltiples plataformas de financiamiento

# Descomenta y añade tu información cuando esté disponible

# GitHub Sponsors
# github: [JosuIru]

# Open Collective
# open_collective: comunidad-viva

# Ko-fi
# ko_fi: comunidadviva

# Tidelift
# tidelift: npm/comunidad-viva

# Community Bridge
# community_bridge: comunidad-viva

# Liberapay
# liberapay: comunidadviva

# IssueHunt
# issuehunt: JosuIru

# Patreon
# patreon: comunidadviva

# Custom URLs (máximo 4)
# custom: ['https://www.paypal.me/example', 'https://buy.stripe.com/example']
