version: '3.8'

services:
  backend:
    build:
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production
    restart: always
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    volumes: []

  frontend:
    build:
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production
    restart: always
    volumes: []

  nginx:
    restart: always

  postgres:
    restart: always

  redis:
    restart: always
