blank_issues_enabled: false
contact_links:
  - name: 📚 Documentación
    url: https://github.com/JosuIru/comunidad-viva/blob/main/README.md
    about: Consulta la documentación del proyecto
  - name: 💬 Discusiones
    url: https://github.com/JosuIru/comunidad-viva/discussions
    about: Únete a las discusiones de la comunidad
